[build]
  # netlify requires a publish directory even if we only care about the functions
  publish = "dist/node-netlify-poc/"

[functions]
  # Sets a custom directory for Netlify Functions
  # directory = "functions/"
  directory = "dist/node-netlify-poc/"

  # Specifies `esbuild` for functions bundling, esbuild is the default for TS
  # node_bundler = "esbuild"

  # Flags "package-1" as an external node module for all functions
  # list of Node.js modules that are copied to the bundled artifact without adjusting their source or references during the bundling process; 
  # only applies when node_bundler is set to esbuild. 
  # This property helps handle dependencies that can’t be inlined, such as modules with native add-ons.
  # external_node_modules = ["package-1"]

  # Includes all Markdown files inside the "files/" directory.
  # lets you specify additional files or directories and reference them dynamically in function code. 
  # staticly referenced files are automatically included in the bundle
  # You can use * to match any character or prefix an entry with ! to exclude files. 
  # Paths are relative to the base directory.
  # included_files = ["files/*.md"]

[functions."api_*"]
  # Apply settings to any functions with a name beginning with "api_"
 
  # Functions matching this pattern have both "package-1" and "package-2" 
  # as external modules, because modules from this object
  # are concatenated with any from the top-level object.
  # external_node_modules = ["package-2"]

  # Includes all Markdown files previously defined in the
  # top-level object, except for "post-1.md".
  # included_files = ["!files/post-1.md"]

[functions.api_payment]
  # Apply settings to a function named "api_payment"
  # Flags "package-3" and "package-4" as external node modules
  # This function has 4 external node modules:
  #  "package-1" from the top-level object
  #  "package-2" from the "api_*" object
  #  "package-3" and "package-4" from this object
  # external_node_modules = ["package-3", "package-4"]

  # Includes all Markdown files inside "files/", except for
  # "post-1.md" (excluded in the "api_*" object)
  # and "post-2.md" (excluded in this object).
  # Also includes "package.json" and any files
  # inside "images/" or any of its subdirectories.
  # included_files = ["!files/post-2.md", "package.json", "images/**"]

